<?php //> Й <- UTF mark

/*

THIS FILE IS A DUMMY. MUST BE BUILT FROM THE DATABASE

report configurations

top-level array items:
	'caption'       => 'client list',                 (required) Report caption, will be attached to HTML title
	'main_table'    => 'clients'                      (required) Primary report table. All other will be joined here
	'id_field'      => 'client_id',                   (required) Report id column, will be used as row ID's
	'sql_select'    => 'select * from clients'        (optional) SQL to use for SELECT instead of autogenerated
	'sql_insert'    => 'select * from clients'        (optional) SQL to use for INSERT instead of autogenerated
	'sql_update'    => 'select * from clients'        (optional) SQL to use for UPDATE instead of autogenerated
	'sql_delete'    => 'select * from clients'        (optional) SQL to use for DELETE instead of autogenerated
	'editor'        => 'xsl/some.xsl'                 (optional) Editorial gialog XSL filename. "editorial.xsl" is the default. Relative path starts from module root
	'context_menu'  => array(...                      (optional) Action list for context menu
	
	context menu items can be defined by the following styles:
		'edit_here',                                    // just a link to an action in "actions.php"
		'sample_action' => array('width'=>100),         // link and override options. For array description, see "actions.php"
		array('caption'=>'hey', 'api'=>'testRecord'),   // in-place action definition
		array(),                                        // divider - no caption set
	
	
	'report_menu'   => array(...                      (optional) Actions for common report menu
	
	'joined_tables' => array(                         (optional) Tables to join ti the main table (or to previously joined)             
		'clients' => array(
			'type'          => 'sql',                 "real" or "sql"
			'sql'           => 'select object_id, group_concat(comment_text, \', \') as comments from comments group by object_id',
			'table'         => '',                    table for the type "real"
			'alias'         => 'comments_synth',      alias to set ( TABLE AS ALIAS )
			'join_field'    => 'object_id',           field to join by (in joined table)
			'join_to_table' => 'clients',             table to join TO
			'join_to_field' => 'id',                  field in join target
			'join_hint'     => 'left',                join hint (LEFT/RIGHT/FULL)
		)
	),
	
	
	'fields'       => array(...                      (required) Fields to include. one may use the same way as with context menu (link and array)

also refer to doc:TAG:FIELDS_AND_MENUS for meanings of "context_menu" and "report_menu" arrays

*/

Registry::Set('api_reports', array(

	///////////////////////////////////////////////////////////////////////////////////////////////
	// clients ////////////////////////////////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////////////////////////////////////////
	'report_clients' => array(
		'caption'       => 'clients',
		'main_table'    => 'clients',
		'id_field'      => 'clients_id',
		'sql_update'    => 'update clients set first_name = :first_name, patronymic = :patronymic, second_name = :second_name, phone = :phone, email = :email, counter = :counter, address = :address, labels = :labels where id = :row_id',
		
		'context_menu' => array(
			'record_add',
			'record_edit',
			'record_delete_confirm',
			'comments_dialog'
		),

		'report_menu' => array(
			'add_record',
			'edit_record'
		),

		'joined_tables' => array(
			'clients' => array(
				'type'          => 'sql',
				'table'         => '',
				'alias'         => 'comments_synth',
				'sql'           => 'select object_id, group_concat(comment_text, \', \') as comments from comments group by object_id',
				'join_field'    => 'object_id',
				'join_to_table' => 'clients',
				'join_to_field' => 'id',
				
			)
		),

		'fields' => array(
			'clients_id'          => array('width'=>'20'),
			'clients_first_name'  => array('width'=>'150'),
			'clients_patronymic'  => array('width'=>'150'),
			'clients_second_name' => array('width'=>'150'),
			'clients_phone'       => array('width'=>'100'),
			'clients_email'       => array('width'=>'100'),
			'clients_counter'     => array('width'=>'80'),
			'clients_address'     => array('width'=>'250'),
			'clients_labels'      => array('width'=>'250'),
			array(
				'table'       => 'comments_synth',
				'table_field' => 'comments',
				'field'       => 'comments',
				'type'        => DB_FIELD_TYPE_TEXT,
				'caption'     => 'Комментарии',
				'out'         => true,
				'width'       => 200,
				'regexp'      => DB_REGEXP_TEXT,
				'readonly'    => true
			)
		)
	),

	///////////////////////////////////////////////////////////////////////////////////////////////
	// messages ///////////////////////////////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////////////////////////////////////////
	'report_messages' => array(
		'caption'       => 'messages list',
		'main_table'    => 'messages',
		'id_field'      => 'messages_id',
		'sql_update'    => 'update mailfrom set caption = :caption, from_addr = :from_addr, server = :server, port = :port, auth_type = :auth_type, ehlo = :ehlo, login = :login, password = :password where id = :row_id',
		'context_menu'  => array(
			'record_delete_confirm'
		),

		'report_menu'   => array(),

		'joined_tables' => array(
			'clients' => array(
				'table'         => 'clients',
				'sql'           => '',
				'join_field'    => 'email',
				'join_to_table' => 'messages',
				'join_to_field' => 'to'
			)
		),
		
		'fields'        => array(
			'messages_id',
			'messages_subject',
			'messages_from',
			'messages_to',
			'messages_datetime',
			'messages_message' => array('out_table' => false),
			'messages_template'
			
		)
	),


	///////////////////////////////////////////////////////////////////////////////////////////////
	// "from" mails ///////////////////////////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////////////////////////////////////////
	'report_mailfrom' => array(
		'caption'       => 'Почтовые адреса',
		'main_table'    => 'mailfrom',
		'id_field'      => 'mailfrom_id',
		'sql_update'    => 'update mailfrom set caption = :caption, from_addr = :from_addr, server = :server, port = :port, auth_type = :auth_type, ehlo = :ehlo, login = :login, password = :password 					 where id = :row_id',
		'context_menu'  => array(
			'record_add',
			'record_edit',
			'record_delete_confirm',
			'comments_dialog',
		),

		'report_menu'   => array(),

		'fields'        => array(
			'mailfrom_id'        => array('width'=>'50'),
			'mailfrom_caption',
			'mailfrom_from_addr' => array('width'=>'150'),
			'mailfrom_server'    => array('width'=>'150'),
			'mailfrom_port'      => array('width'=>'50'),
			'mailfrom_auth_type' => array('width'=>'150'),
			'mailfrom_ehlo'      => array('width'=>'100'),
			'mailfrom_login'     => array('width'=>'150'),
			'mailfrom_password'  => array('width'=>'100')
		)
	),


	///////////////////////////////////////////////////////////////////////////////////////////////
	// message templates //////////////////////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////////////////////////////////////////
	'report_templates' => array(
		'caption'       => 'Шаблоны сообщений',
		'main_table'    => 'templates',
		'id_field'      => 'templates_id',
		'editor'        => 'xsl/editor_templates.xsl',
		'sql_update'    => 'update templates set caption = :caption, message = :message where id = :row_id',

		'joined_tables' => array(
			'clients' => array(
				'type'          => 'sql',
				'table'         => '',
				'alias'         => 'comments_synth',
				'sql'           => 'select object_id, group_concat(comments.attached_name, \', \') as attachments from comments group by object_id',
				'join_field'    => 'object_id',
				'join_to_table' => 'templates',
				'join_to_field' => 'id',
			)
		),

		'context_menu'  => array(
			'record_add',
			'record_edit',
			'comments_dialog',
			'template_to_message_dialog',
			'record_delete_confirm'
		),

		'report_menu'   => array(),

		'fields'        => array(
			'templates_id' => array('width'=>'20'),
			'templates_caption',
			'templates_message',
			'templates_attachments' => array(
				'table'       => 'comments_synth',
				'table_field' => 'attachments',
				'field'       => 'attachments',
				'type'        => DB_FIELD_TYPE_TEXT,
				'caption'     => 'Прикрепленные файлы',
				'width'       => 200,
				'regexp'      => DB_REGEXP_TEXT
			)
		)
	),

	///////////////////////////////////////////////////////////////////////////////////////////////
	// comments ///////////////////////////////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////////////////////////////////////////
	'report_comments' => array(
		'caption'       => 'Комментарии',
		'main_table'    => 'comments',
		'id_field'      => 'comments_id',

		'context_menu'  => array(
			'record_edit',
			'record_delete_confirm'
		),

		'report_menu'   => array(),

		'fields'        => array(
			'comments_id',
			'comments_object_id',
			'comments_user_id',
			'comments_stamp',
			'comments_comment_text',
			'comments_attached_name',
			'comments_comment_state'
		)
	)

));


?>